name: planner
description: "Plain organizer for your phone"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  uuid: 4.0.0
  flutter_simple_dependency_injection: 2.0.0
  provider: 6.0.5
  flutter_contacts: 1.1.7+1
  flutter_slidable: 3.0.0
  intl: 0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
